### PR TITLE
Add helper.R testing example. Fixes #26

### LINKED ISSUE #26: vignette for simple use cases?
I thought the [vignette](https://krlmlr.github.io/rprojroot/articles/rprojroot.html) was helpful. Perhaps some very short examples could also be helpful? 

Here's a very short, concrete example that for the user would be:
    - useful and important
    - easy to implement
so I think it would be a great way to show off the utility/power/ease of `rprojroot`

I was able to get this working for my use case in one-line of code. I have a package and I have some baseline data for unit tests that I was storing in an .Rds file:

```
output <- myFun(stuff)

## a one-liner with rprojroot
baseline_test_data_file <- rprojroot::find_testthat_root_file("baseline_test_data.Rds")
## now load that data
baseline_test_data <- readRDS(file = baseline_test_data_file)
## and use it
testthat::test_that(
  "myFun returns correct output",
  testthat::expect_equal(
    output,
    baseline_test_data
  )
)
```

Previously, I had some if-then syntax for whether I was running interactively or via `devtools::test()`. Basically, I'd try to determine what the working directory was, and then specify the relative path from that; i think rprojroot does ~ exactly this, but with one line. 

```
nc <- nchar(getwd())
if (substr(getwd, nc-7,nc)=="testthat") { ## called from devtools::test()
   relative_path_name <- "baseline_test_data.Rds"
} else 
if (substr(getwd, nc-4,nc)=="mypkg") { ## running interactively 
   relative_path_name <- "tests/testthat/baseline_test_data.Rds"
}
baseline_test_data <- readRDS(file = baseline_test_data_file)
```

So I replaced the above with the below:

```
baseline_test_data_file <- rprojroot::find_testthat_root_file("baseline_test_data.Rds")
baseline_test_data <- readRDS(file = baseline_test_data_file)
```

I can write up a short vignette & start a PR if you'd like. Thanks for making my life better!

### PR DESCRIPTION
**Pull request by BarkleyBG**
I tried to keep it short and sweet. Let me know what you think?

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. It feels that this has applications beyond testing: Basically in any situation where you want to lookup files in a known subdirectory. I wonder if we should add a `subdir` argument to the `make_find_file()` and `make_fix_file()` accessors, and extend the vignette accordingly.

**Comment by BarkleyBG** [comment]
I was looking into the guts to see if I could understand the `make_find_file()` and `make_fix_file()` better. I still don't fully understand all the moving parts, so I don't know if I can respond to your suggestion to add the `subdir` argument.

I'd be happy to keep thinking on your comment re: `subdir` argument, but I'm not sure how much help I am at this moment.

**Comment by BarkleyBG** [comment]
While I was reading around the guts, I put some pieces together in my understanding of the package, and I thought that it would be good to expand upon the vignette's first example a little bit, which I did here. You'll note that I didn't attempt to mimic the working directory issues by explicity calling `setwd()` or anything, but I thought this was a clean-ish way to demonstrate how `rprojroot` can help stop the working directory insanity.

**Comment by BarkleyBG** [comment]
In general, my understanding is that `rprojroot` has two actions:

1. Finds the root file 
    - this is the most important action, really
2. Uses a wrapper to `file.path()` to specify relative paths from the root to the desired file.
    - This supposes that the directory/tree structure is known. 

I would imagine you could have a lot of functionality where the directory/tree structure isn't fully known, and you need to blindly search for files that match certain characteristics, but I don't think that's important at the moment. I think that this package should solve the "unknown working directory in a known tree/directory structure" problem (for now).

Do you think I've got the right idea here? Perhaps this helps to clarify what the features of the package should be (especially w/r/t the `subdir` consideration).

**Comment by krlmlr** [comment]
Thanks. Here's what I see:

```r
rprojroot::is_testthat$make_fix_file()
## function (...) {
##   file.path("/.../rprojroot/tests/testthat", ...)
## }
```

What if we had:

```r
rprojroot::is_testthat$make_fix_file(subdir = "testing_data")
## function (...) {
##   file.path("/.../rprojroot/tests/testthat", "testing_data", ...)
## }
```

That would just create the `get_my_path()` function:

```r
get_my_path <- rprojroot::is_testthat$make_fix_file(subdir = "testing_data")
```

I think you have a good understanding of the package's goals, hope the examples made it a bit clearer what I meant with the `subdir` argument.

I'm fine with the first part, will merge now and revert partially. Would you like to submit a PR for the second part, maybe after we add support for `subdir`?

**Comment by krlmlr** [comment]
Decided to also keep the second section, we can tweak once we have a `subdir` argument. May I add you as co-author to the vignette?

**Comment by BarkleyBG** [comment]
I'm happy to help moving this along!

1. Yes, I like `subdir`. If it's a nested subdirectory, should `subdir` take a list or vector argument? And could this work for e.g.:

```
my_subdir <- c("..", "sister_dir", "sister_subdir")
```

2. Yes, please add me as co-vign-author! Thanks!

I'm out of office a little bit right now but would be happy to help where I can later this month. Feel free to tag @ me in issues and I'll respond.

**Pull request merged**
